### ISSUE TITLE
Принять решение по архитектуре

### ISSUE THREAD

**Issue by KletskovG** [KletskovG/StudentHelper#17]
Продумать базовые маршруты для каждого из модулей
#####  Необходимо
- [ ] Необходимо ли всем модулям делать базовый роут /api
- [x] Сообщить о принятом решении команде
- [x] Просто описать базовые соглашения по роутингу backend сервисов

**Comment by sickwick** [comment]
Маршруты описаны в документе в беседе

**Comment by KletskovG** [comment]
[Архитектура и правила .docx](https://github.com/KletskovG/StudentHelper/files/4557214/default.docx)
